package entity;

public enum CommandType {
    INVENTARIO, APRI, CAMMINA, OSSERVA, USA, PARLA, TOCCA, COLLEGA, SPINGI, PRENDI, COSTRUISCI, CERCA, RIPARA, RIFIUTA, ACCETTA,
    ROVESCIA, BEVI, ATTACCA, CHIAMA, HELP, CEDI, TORNA, SPECIALE
}
